//! G-code static validation (flavor + bounds + temp sanity).

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GcodeFlavor {
    Marlin,
    Klipper,
    Bambu,
    Unknown,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GcodeReport {
    pub ok: bool,
    pub flavor: GcodeFlavor,
    pub lines: usize,
    pub move_count: usize,
    pub bbox_mm: Option<[f64; 6]>, // xmin xmax ymin ymax zmin zmax
    pub max_temp_c: Option<f64>,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct PrinterVolume {
    pub x_mm: f64,
    pub y_mm: f64,
    pub z_mm: f64,
    pub max_hotend_c: f64,
    pub max_bed_c: f64,
}

impl Default for PrinterVolume {
    fn default() -> Self {
        // generic X1C-ish envelope for checks
        Self {
            x_mm: 256.0,
            y_mm: 256.0,
            z_mm: 256.0,
            max_hotend_c: 300.0,
            max_bed_c: 110.0,
        }
    }
}

pub fn check_gcode(text: &str, volume: &PrinterVolume) -> GcodeReport {
    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    let mut flavor = GcodeFlavor::Unknown;
    let mut moves = 0usize;
    let mut xmin = f64::INFINITY;
    let mut xmax = f64::NEG_INFINITY;
    let mut ymin = f64::INFINITY;
    let mut ymax = f64::NEG_INFINITY;
    let mut zmin = f64::INFINITY;
    let mut zmax = f64::NEG_INFINITY;
    let mut max_temp = 0.0f64;
    let mut saw_g = false;
    let mut x = 0.0f64;
    let mut y = 0.0f64;
    let mut z = 0.0f64;

    let lower = text.to_ascii_lowercase();
    if lower.contains("bambu") || lower.contains("; GENERATED BY BAMBU") {
        flavor = GcodeFlavor::Bambu;
    } else if lower.contains("klipper") || lower.contains("set_velocity_limit") {
        flavor = GcodeFlavor::Klipper;
    } else if lower.contains("marlin") || lower.contains("m104") || lower.contains("g28") {
        flavor = GcodeFlavor::Marlin;
    }

    let lines: Vec<&str> = text.lines().collect();
    if lines.is_empty() {
        errors.push("empty gcode".into());
    }

    for (i, raw) in lines.iter().enumerate() {
        let line_no = i + 1;
        let s = raw.split(';').next().unwrap_or("").trim();
        if s.is_empty() {
            continue;
        }
        let up = s.to_ascii_uppercase();
        if up.starts_with('G') || up.starts_with('M') {
            saw_g = true;
        }
        // proprietary / dangerous-ish
        if up.contains("M112") {
            warnings.push(format!("line {line_no}: emergency stop M112 present"));
        }
        if up.starts_with("G0")
            || up.starts_with("G1")
            || up.starts_with("G2")
            || up.starts_with("G3")
        {
            moves += 1;
            if let Some(v) = parse_word(s, 'X') {
                x = v;
            }
            if let Some(v) = parse_word(s, 'Y') {
                y = v;
            }
            if let Some(v) = parse_word(s, 'Z') {
                z = v;
            }
            xmin = xmin.min(x);
            xmax = xmax.max(x);
            ymin = ymin.min(y);
            ymax = ymax.max(y);
            zmin = zmin.min(z);
            zmax = zmax.max(z);
        }
        if up.starts_with("M104")
            || up.starts_with("M109")
            || up.starts_with("M140")
            || up.starts_with("M190")
        {
            if let Some(t) = parse_word(s, 'S') {
                max_temp = max_temp.max(t);
                if up.starts_with("M104") || up.starts_with("M109") {
                    if t > volume.max_hotend_c + 1e-6 {
                        errors.push(format!(
                            "line {line_no}: hotend temp {t} > max {}",
                            volume.max_hotend_c
                        ));
                    }
                } else if t > volume.max_bed_c + 1e-6 {
                    errors.push(format!(
                        "line {line_no}: bed temp {t} > max {}",
                        volume.max_bed_c
                    ));
                }
            }
        }
    }

    if !saw_g {
        errors.push("no G/M commands found".into());
    }
    if moves == 0 {
        warnings.push("no G0/G1 moves found".into());
    }

    let bbox = if moves > 0 {
        if xmax > volume.x_mm + 1e-3 || ymax > volume.y_mm + 1e-3 || zmax > volume.z_mm + 1e-3 {
            errors.push(format!(
                "moves exceed volume {}x{}x{} (bbox max {:.2},{:.2},{:.2})",
                volume.x_mm, volume.y_mm, volume.z_mm, xmax, ymax, zmax
            ));
        }
        if xmin < -1e-3 || ymin < -1e-3 || zmin < -1e-3 {
            warnings.push(format!(
                "negative coordinates in bbox min {:.2},{:.2},{:.2}",
                xmin, ymin, zmin
            ));
        }
        Some([xmin, xmax, ymin, ymax, zmin, zmax])
    } else {
        None
    };

    GcodeReport {
        ok: errors.is_empty(),
        flavor,
        lines: lines.len(),
        move_count: moves,
        bbox_mm: bbox,
        max_temp_c: if max_temp > 0.0 { Some(max_temp) } else { None },
        errors,
        warnings,
    }
}

pub(crate) fn parse_word(line: &str, key: char) -> Option<f64> {
    let upkey = key.to_ascii_uppercase();
    for tok in line.split_whitespace() {
        let t = tok.as_bytes();
        if t.is_empty() {
            continue;
        }
        if t[0].to_ascii_uppercase() as char == upkey {
            return tok[1..].parse().ok();
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn simple_marlin_ok() {
        let g = "G28\nM104 S200\nG1 X10 Y10 Z0.2 F1200\nG1 X20 Y10 E0.5\n";
        let r = check_gcode(g, &PrinterVolume::default());
        assert!(r.ok, "{r:?}");
        assert!(r.move_count >= 2);
    }

    #[test]
    fn oversize_fails() {
        let g = "G1 X900 Y10 Z0.2\n";
        let r = check_gcode(g, &PrinterVolume::default());
        assert!(!r.ok);
    }

    #[test]
    fn property_junk_gcode_no_panic() {
        let long = "G1 X1\n".repeat(5000);
        let samples = [
            "",
            "\0\0",
            "G1 Xnotanum\n",
            long.as_str(),
            "M104 S9999\nG1 X1 Y1 Z1\n",
            ";;;;;;;;\n",
            "G1 X-1 Y-1 Z-1\n",
        ];
        for (i, s) in samples.iter().enumerate() {
            let r = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                let _ = check_gcode(s, &PrinterVolume::default());
            }));
            assert!(r.is_ok(), "gcode panicked on sample {i}");
        }
    }
}
